import = [ "~/.config/alacritty/themes/themes/nordic.toml"
]
live_config_reload = true

[shell]
program = "/opt/homebrew/bin/bash"
args = ["-l", "-c", "tmux new-session -A -s bern"]
[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false

[window.dimensions]
lines = 40
columns = 120

[window.padding]
x = 20
y = 10

[font]
size = 13.0

[font.bold]
family = "SF Mono"
style = "Heavy"

[font.bold_italic]
family = "SF Mono"
style = "Heavy Italic"

[font.italic]
family = "SF Mono"
style = "Semibold Italic"

[font.normal]
family = "SF Mono"
style = "Semibold"
